language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

script: make test

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode9.4        
        
before_install:
    - eval "${MATRIX_EVAL}"
